nodeLinker: node-modules

# Suppress peer dependency warnings for eslint-plugin-import
# (plugin declares support up to eslint v9, but works correctly with v10)
logFilters:
  - code: YN0060
    level: discard
  - code: YN0086
    level: discard
